name: CI

on: [pull_request, issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, $(whoami), $(ip addr show), $(ls -a) from GITHUB Build Server!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Deploying to Container
      run: |
        echo ls -a
        cd ./asp/ASP/aspnetapp/aspnetapp/Tailspin.SpaceGame.Web/
    - name: Docker Push
      uses: opspresso/action-docker@v0.2.6
      with:
        # Your Docker Registry Type.
        registry-type:  --docker
