name: CI

on: [issue_comment, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, $(whoami), $(ip addr show), $(ls -a) from GITHUB Build Server!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Deploying to Container
      run: |
        echo ls -a
        cd /home/runner/work/ASP/ASP/aspnetapp/aspnetapp/Tailspin.SpaceGame.Web/
        docker build -t aspnetapp .
        docker run -d -p 8080:80 --name myapp aspnetapp
        curl localhost:8080 | less
    - name: ECS deploy
      uses: brunocascio/ecs-deploy@v1.1.1
      with:
        # Cluster name where service/task will be deployed
        cluster: ASP1
        # Service name of the service/task to be deployed
        service: test
        # Task definition name to be updated
        task: 4cebbf6a-7d1c-4bb3-8fa7-3c7dd32c5783
        # Container name to be updated
        container: test
        # Env file path
                # Deployment timeout (default 300)
        
